name: Newman Test Run
on:
  push:
    branches:
    - development
  pull_request:
    branches:
    - development
jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: matt-ball/newman-action@master
        with:
          collection: LERT/backend/postman_collection.json
          environment: LERT/backend/postman_environment.json
